# help http://blog.dscpl.com.au/2015/06/proxying-to-python-web-application.html
version: "3.3"

services:
  web:
    build: web
    networks:
      - internal
      - external
    ports: 
      - "80:8000"
    volumes:
      - "./web:/webapp"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - internal
    restart: always
    volumes:
      - "./db:/var/lib/postgresql/data"
  
  dns_hijack:
    build: dns_hijack
    networks:
      -external

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
