#!/bin/bash

function rand255() {
    printf $((1 + RANDOM % 255))
}

[[ -z $1 ]] &&
    echo You must specify how many ip to generate &&
    exit

for (( i = 0; i <= $1; i++ ))
do
    rand255
    printf .
    rand255
    printf .
    rand255
    printf .
    rand255
    echo
done
